# Generated by Django 4.2.26 on 2025-11-21 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратная связь",
            },
        ),
        migrations.AlterModelOptions(
            name="table",
            options={"verbose_name": "Столик", "verbose_name_plural": "Столики"},
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="duration_hours",
            field=models.PositiveIntegerField(verbose_name="Продолжительность (часов)"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_time",
            field=models.TimeField(verbose_name="Время окончания"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guests_count",
            field=models.PositiveIntegerField(verbose_name="Количество гостей"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="special_requests",
            field=models.TextField(blank=True, verbose_name="Особые пожелания"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_time",
            field=models.TimeField(verbose_name="Время начала"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("active", "Активно"), ("cancelled", "Отменено")],
                default="active",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.table",
                verbose_name="Столик",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.TextField(verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="table",
            name="capacity",
            field=models.PositiveIntegerField(
                choices=[
                    (2, "2 человека"),
                    (4, "4 человека"),
                    (6, "6 человек"),
                    (8, "8 человек"),
                ],
                verbose_name="Вместимость",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="table",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="table",
            name="is_vip",
            field=models.BooleanField(default=False, verbose_name="VIP столик"),
        ),
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.PositiveIntegerField(
                unique=True, verbose_name="Номер столика"
            ),
        ),
    ]
