# Generated by Django 4.2.26 on 2025-11-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_booking_options_alter_feedback_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратные связи",
            },
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="phone",
        ),
    ]
