# Generated by Django 4.2.26 on 2025-11-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_feedback_options_remove_feedback_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратная связь",
            },
        ),
    ]
