# Generated by Django 4.2.26 on 2025-11-29 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0004_alter_feedback_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-date", "-start_time"],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.RemoveField(
            model_name="booking",
            name="duration_hours",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="special_requests",
        ),
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="table",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tables/"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guests_count",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="booking",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booking.table"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="table",
            name="capacity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="table",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="table",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="table",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.IntegerField(unique=True),
        ),
    ]
