# Generated by Django 4.2.26 on 2025-12-01 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0005_alter_booking_options_alter_feedback_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_time",
            field=models.TimeField(verbose_name="Время окончания"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guests_count",
            field=models.IntegerField(verbose_name="Количество гостей"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_time",
            field=models.TimeField(verbose_name="Время начала"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                default="active", max_length=20, verbose_name="Статус"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.table",
                verbose_name="Столик",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.TextField(verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="table",
            name="capacity",
            field=models.IntegerField(verbose_name="Вместимость"),
        ),
        migrations.AlterField(
            model_name="table",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="table",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="tables/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="table",
            name="is_vip",
            field=models.BooleanField(default=False, verbose_name="VIP"),
        ),
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.IntegerField(unique=True, verbose_name="Номер столика"),
        ),
    ]
