# Generated by Django 4.2.26 on 2025-12-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_alter_booking_created_at_alter_booking_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="special_requests",
            field=models.TextField(
                blank=True, null=True, verbose_name="Специальные пожелания"
            ),
        ),
    ]
