# Generated by Django 4.2.26 on 2025-12-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_booking_special_requests"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_table_capacity",
                    models.IntegerField(
                        default=12, verbose_name="Максимальная вместимость столика"
                    ),
                ),
                (
                    "table_capacities",
                    models.JSONField(
                        default=list,
                        help_text="В формате [2, 4, 6, 8, 10, 12]",
                        verbose_name="Доступные вместимости столиков",
                    ),
                ),
                (
                    "booking_statuses",
                    models.JSONField(
                        default=list,
                        help_text="В формате ['active', 'cancelled']",
                        verbose_name="Статусы бронирований",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки ресторана",
                "verbose_name_plural": "Настройки ресторана",
            },
        ),
    ]
