# Generated by Django 4.2.26 on 2025-12-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_restaurantsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="status",
        ),
    ]
